export const API_SIGNIN_REQUEST = 'API_SIGNIN_REQUEST';
export const API_SIGNIN_SUCCESS = 'API_SIGNIN_SUCCESS';
export const API_SIGNIN_FAIL = 'API_SIGNIN_FAIL';

export const API_UPDATE_REQUEST = 'API_UPDATE_REQUEST';
export const API_UPDATE_SUCCESS = 'API_UPDATE_SUCCESS';
export const API_UPDATE_FAIL = 'API_UPDATE_FAIL';

export const API_REGISTER_REQUEST = 'API_REGISTER_REQUEST';
export const API_REGISTER_SUCCESS = 'API_REGISTER_SUCCESS';
export const API_REGISTER_FAIL = 'API_REGISTER_FAIL';

export const API_LOGOUT = 'API_LOGOUT';